"""cartola_diaria table

Revision ID: 02661b49a7bf
Revises: 74af266f28fb
Create Date: 2026-06-03 21:08:54.283963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02661b49a7bf'
down_revision: Union[str, None] = '74af266f28fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartola_diaria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('run_adm', sa.String(length=20), nullable=True),
    sa.Column('nom_adm', sa.String(length=255), nullable=True),
    sa.Column('moneda', sa.String(length=20), nullable=True),
    sa.Column('cuotas_aportadas', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('cuotas_rescatadas', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('cuotas_en_circulacion', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('valor_cuota', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('patrimonio_neto', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('activo_tot', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('num_participes', sa.Integer(), nullable=True),
    sa.Column('num_participes_inst', sa.Integer(), nullable=True),
    sa.Column('rem_fija', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('rem_variable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gastos_afectos', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gastos_no_afectos', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('comision_inversion', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('comision_rescate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('factor_ajuste', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('factor_reparto', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('inversion_en_fondos', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('participes_inst', sa.String(length=1), nullable=True),
    sa.Column('fondo_pen', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'run_fondo', 'serie', name='uq_cartola_fecha_fondo_serie')
    )
    op.create_index(op.f('ix_cartola_diaria_fecha'), 'cartola_diaria', ['fecha'], unique=False)
    op.create_index(op.f('ix_cartola_diaria_run_fondo'), 'cartola_diaria', ['run_fondo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartola_diaria_run_fondo'), table_name='cartola_diaria')
    op.drop_index(op.f('ix_cartola_diaria_fecha'), table_name='cartola_diaria')
    op.drop_table('cartola_diaria')
    # ### end Alembic commands ###
