"""add carteras tables

Revision ID: 0c3bf6dfc418
Revises: 68b11daae46c
Create Date: 2026-06-03 23:01:36.253616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c3bf6dfc418'
down_revision: Union[str, None] = '68b11daae46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartera_extr',
    sa.Column('ffm_6020100', sa.Text(), nullable=True),
    sa.Column('ffm_6020200', sa.Text(), nullable=True),
    sa.Column('ffm_6020300', sa.Text(), nullable=True),
    sa.Column('ffm_6020400', sa.Text(), nullable=True),
    sa.Column('ffm_6020500', sa.Text(), nullable=True),
    sa.Column('ffm_6020600', sa.Text(), nullable=True),
    sa.Column('ffm_6020700', sa.Text(), nullable=True),
    sa.Column('ffm_6020800', sa.Text(), nullable=True),
    sa.Column('ffm_6020900', sa.Text(), nullable=True),
    sa.Column('ffm_6021000', sa.Text(), nullable=True),
    sa.Column('ffm_tir_6021111', sa.Text(), nullable=True),
    sa.Column('ffm_par_6021111', sa.Text(), nullable=True),
    sa.Column('ffm_rel_6021111', sa.Text(), nullable=True),
    sa.Column('ffm_6021112', sa.Text(), nullable=True),
    sa.Column('ffm_6021113', sa.Text(), nullable=True),
    sa.Column('ffm_6021114', sa.Text(), nullable=True),
    sa.Column('ffm_6021200', sa.Text(), nullable=True),
    sa.Column('ffm_6021300', sa.Text(), nullable=True),
    sa.Column('ffm_6021400', sa.Text(), nullable=True),
    sa.Column('ffm_6021511', sa.Text(), nullable=True),
    sa.Column('ffm_6021512', sa.Text(), nullable=True),
    sa.Column('ffm_6021513', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartera_extr_periodo', 'cartera_extr', ['periodo'], unique=False)
    op.create_table('cartera_futu',
    sa.Column('ffm_6040111', sa.Text(), nullable=True),
    sa.Column('ffm_6040112', sa.Text(), nullable=True),
    sa.Column('ffm_6040113', sa.Text(), nullable=True),
    sa.Column('ffm_6040114', sa.Text(), nullable=True),
    sa.Column('ffm_6040115', sa.Text(), nullable=True),
    sa.Column('ffm_6040116', sa.Text(), nullable=True),
    sa.Column('ffm_6040200', sa.Text(), nullable=True),
    sa.Column('ffm_6040300', sa.Text(), nullable=True),
    sa.Column('ffm_6040400', sa.Text(), nullable=True),
    sa.Column('ffm_6040500', sa.Text(), nullable=True),
    sa.Column('ffm_6040600', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartera_futu_periodo', 'cartera_futu', ['periodo'], unique=False)
    op.create_table('cartera_naci',
    sa.Column('ffm_6010100', sa.Text(), nullable=True),
    sa.Column('ffm_6010211', sa.Text(), nullable=True),
    sa.Column('ffm_6010212', sa.Text(), nullable=True),
    sa.Column('ffm_6010300', sa.Text(), nullable=True),
    sa.Column('ffm_6010400', sa.Text(), nullable=True),
    sa.Column('ffm_6010500', sa.Text(), nullable=True),
    sa.Column('ffm_6010600', sa.Text(), nullable=True),
    sa.Column('ffm_6010700', sa.Text(), nullable=True),
    sa.Column('ffm_6010800', sa.Text(), nullable=True),
    sa.Column('ffm_6010900', sa.Text(), nullable=True),
    sa.Column('ffm_6011000', sa.Text(), nullable=True),
    sa.Column('ffm_tir_6011111', sa.Text(), nullable=True),
    sa.Column('ffm_par_6011111', sa.Text(), nullable=True),
    sa.Column('ffm_rel_6011111', sa.Text(), nullable=True),
    sa.Column('ffm_6011112', sa.Text(), nullable=True),
    sa.Column('ffm_6011113', sa.Text(), nullable=True),
    sa.Column('ffm_6011114', sa.Text(), nullable=True),
    sa.Column('ffm_6011200', sa.Text(), nullable=True),
    sa.Column('ffm_6011300', sa.Text(), nullable=True),
    sa.Column('ffm_6011400', sa.Text(), nullable=True),
    sa.Column('ffm_6011511', sa.Text(), nullable=True),
    sa.Column('ffm_6011512', sa.Text(), nullable=True),
    sa.Column('ffm_6011513', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartera_naci_periodo', 'cartera_naci', ['periodo'], unique=False)
    op.create_table('cartera_opci',
    sa.Column('ffm_6030111', sa.Text(), nullable=True),
    sa.Column('ffm_6030112', sa.Text(), nullable=True),
    sa.Column('ffm_6030113', sa.Text(), nullable=True),
    sa.Column('ffm_6030114', sa.Text(), nullable=True),
    sa.Column('ffm_6030115', sa.Text(), nullable=True),
    sa.Column('ffm_6030116', sa.Text(), nullable=True),
    sa.Column('ffm_6030200', sa.Text(), nullable=True),
    sa.Column('ffm_6030300', sa.Text(), nullable=True),
    sa.Column('ffm_6030400', sa.Text(), nullable=True),
    sa.Column('ffm_6030500', sa.Text(), nullable=True),
    sa.Column('ffm_6030600', sa.Text(), nullable=True),
    sa.Column('ffm_6030700', sa.Text(), nullable=True),
    sa.Column('ffm_6030800', sa.Text(), nullable=True),
    sa.Column('ffm_6030900', sa.Text(), nullable=True),
    sa.Column('ffm_6031000', sa.Text(), nullable=True),
    sa.Column('ffm_6031100', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartera_opci_periodo', 'cartera_opci', ['periodo'], unique=False)
    op.create_table('cartera_opla',
    sa.Column('ffm_6050111', sa.Text(), nullable=True),
    sa.Column('ffm_6050112', sa.Text(), nullable=True),
    sa.Column('ffm_6050113', sa.Text(), nullable=True),
    sa.Column('ffm_6050114', sa.Text(), nullable=True),
    sa.Column('ffm_6050115', sa.Text(), nullable=True),
    sa.Column('ffm_6050116', sa.Text(), nullable=True),
    sa.Column('ffm_6050200', sa.Text(), nullable=True),
    sa.Column('ffm_6050300', sa.Text(), nullable=True),
    sa.Column('ffm_6050400', sa.Text(), nullable=True),
    sa.Column('ffm_6050500', sa.Text(), nullable=True),
    sa.Column('ffm_6050600', sa.Text(), nullable=True),
    sa.Column('ffm_6050700', sa.Text(), nullable=True),
    sa.Column('ffm_6050800', sa.Text(), nullable=True),
    sa.Column('ffm_6050900', sa.Text(), nullable=True),
    sa.Column('ffm_6051000', sa.Text(), nullable=True),
    sa.Column('ffm_6051100', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartera_opla_periodo', 'cartera_opla', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cartera_opla_periodo', table_name='cartera_opla')
    op.drop_table('cartera_opla')
    op.drop_index('ix_cartera_opci_periodo', table_name='cartera_opci')
    op.drop_table('cartera_opci')
    op.drop_index('ix_cartera_naci_periodo', table_name='cartera_naci')
    op.drop_table('cartera_naci')
    op.drop_index('ix_cartera_futu_periodo', table_name='cartera_futu')
    op.drop_table('cartera_futu')
    op.drop_index('ix_cartera_extr_periodo', table_name='cartera_extr')
    op.drop_table('cartera_extr')
    # ### end Alembic commands ###
