"""drop redundant cartola columns

Revision ID: 478f23a5c713
Revises: 639c95e441b2
Create Date: 2026-06-06 15:49:46.852007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '478f23a5c713'
down_revision: Union[str, None] = '639c95e441b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartola_diaria', 'comision_inversion')
    op.drop_column('cartola_diaria', 'run_adm')
    op.drop_column('cartola_diaria', 'comision_rescate')
    op.drop_column('cartola_diaria', 'nom_adm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartola_diaria', sa.Column('nom_adm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cartola_diaria', sa.Column('comision_rescate', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True))
    op.add_column('cartola_diaria', sa.Column('run_adm', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('cartola_diaria', sa.Column('comision_inversion', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
