"""add composite indexes and monto generated columns

Revision ID: 5880f3682e10
Revises: fa83108ba94b
Create Date: 2026-06-07 13:56:51.675178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5880f3682e10'
down_revision: Union[str, None] = 'fa83108ba94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartera_extr_run_fondo'), table_name='cartera_extr')
    op.create_index('ix_cartera_extr_run_fondo_periodo', 'cartera_extr', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_fi_ext_run_fondo'), table_name='cartera_fi_ext')
    op.create_index('ix_cartera_fi_ext_run_fondo_periodo', 'cartera_fi_ext', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_fi_fut_fw_run_fondo'), table_name='cartera_fi_fut_fw')
    op.create_index('ix_cartera_fi_fut_fw_run_fondo_periodo', 'cartera_fi_fut_fw', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_fi_met_part_run_fondo'), table_name='cartera_fi_met_part')
    op.create_index('ix_cartera_fi_met_part_run_fondo_periodo', 'cartera_fi_met_part', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_fi_nac_run_fondo'), table_name='cartera_fi_nac')
    op.create_index('ix_cartera_fi_nac_run_fondo_periodo', 'cartera_fi_nac', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_futu_run_fondo'), table_name='cartera_futu')
    op.create_index('ix_cartera_futu_run_fondo_periodo', 'cartera_futu', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_naci_run_fondo'), table_name='cartera_naci')
    op.create_index('ix_cartera_naci_run_fondo_periodo', 'cartera_naci', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_opci_run_fondo'), table_name='cartera_opci')
    op.create_index('ix_cartera_opci_run_fondo_periodo', 'cartera_opci', ['run_fondo', 'periodo'], unique=False)
    op.drop_index(op.f('ix_cartera_opla_run_fondo'), table_name='cartera_opla')
    op.create_index('ix_cartera_opla_run_fondo_periodo', 'cartera_opla', ['run_fondo', 'periodo'], unique=False)
    op.add_column('cartola_diaria', sa.Column('monto_aportado', sa.Numeric(precision=28, scale=2), sa.Computed('cuotas_aportadas * valor_cuota', persisted=True), nullable=True))
    op.add_column('cartola_diaria', sa.Column('monto_rescatado', sa.Numeric(precision=28, scale=2), sa.Computed('cuotas_rescatadas * valor_cuota', persisted=True), nullable=True))
    op.drop_index(op.f('ix_cartola_diaria_run_fondo'), table_name='cartola_diaria')
    op.create_index('ix_cartola_diaria_run_fondo_fecha', 'cartola_diaria', ['run_fondo', 'fecha'], unique=False)
    op.create_index('ix_fondos_inversion_administrador', 'fondos_inversion', ['administrador'], unique=False)
    op.create_index('ix_fondos_inversion_vigente_rescatable', 'fondos_inversion', ['vigente', 'rescatable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fondos_inversion_vigente_rescatable', table_name='fondos_inversion')
    op.drop_index('ix_fondos_inversion_administrador', table_name='fondos_inversion')
    op.drop_index('ix_cartola_diaria_run_fondo_fecha', table_name='cartola_diaria')
    op.create_index(op.f('ix_cartola_diaria_run_fondo'), 'cartola_diaria', ['run_fondo'], unique=False)
    op.drop_column('cartola_diaria', 'monto_rescatado')
    op.drop_column('cartola_diaria', 'monto_aportado')
    op.drop_index('ix_cartera_opla_run_fondo_periodo', table_name='cartera_opla')
    op.create_index(op.f('ix_cartera_opla_run_fondo'), 'cartera_opla', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_opci_run_fondo_periodo', table_name='cartera_opci')
    op.create_index(op.f('ix_cartera_opci_run_fondo'), 'cartera_opci', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_naci_run_fondo_periodo', table_name='cartera_naci')
    op.create_index(op.f('ix_cartera_naci_run_fondo'), 'cartera_naci', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_futu_run_fondo_periodo', table_name='cartera_futu')
    op.create_index(op.f('ix_cartera_futu_run_fondo'), 'cartera_futu', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_fi_nac_run_fondo_periodo', table_name='cartera_fi_nac')
    op.create_index(op.f('ix_cartera_fi_nac_run_fondo'), 'cartera_fi_nac', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_fi_met_part_run_fondo_periodo', table_name='cartera_fi_met_part')
    op.create_index(op.f('ix_cartera_fi_met_part_run_fondo'), 'cartera_fi_met_part', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_fi_fut_fw_run_fondo_periodo', table_name='cartera_fi_fut_fw')
    op.create_index(op.f('ix_cartera_fi_fut_fw_run_fondo'), 'cartera_fi_fut_fw', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_fi_ext_run_fondo_periodo', table_name='cartera_fi_ext')
    op.create_index(op.f('ix_cartera_fi_ext_run_fondo'), 'cartera_fi_ext', ['run_fondo'], unique=False)
    op.drop_index('ix_cartera_extr_run_fondo_periodo', table_name='cartera_extr')
    op.create_index(op.f('ix_cartera_extr_run_fondo'), 'cartera_extr', ['run_fondo'], unique=False)
    # ### end Alembic commands ###
