"""add tipo_serie to nemotecnicos

Revision ID: 639c95e441b2
Revises: 2b01163a2b6a
Create Date: 2026-06-06 15:21:14.177610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '639c95e441b2'
down_revision: Union[str, None] = '2b01163a2b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nemotecnicos', sa.Column('tipo_serie', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nemotecnicos', 'tipo_serie')
    # ### end Alembic commands ###
