"""add nemotecnicos table

Revision ID: 68b11daae46c
Revises: 02661b49a7bf
Create Date: 2026-06-03 22:44:41.700927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68b11daae46c'
down_revision: Union[str, None] = '02661b49a7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nemotecnicos',
    sa.Column('nemotecnico', sa.String(length=20), nullable=False),
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('dv_fondo', sa.String(length=5), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('nombre_fondo', sa.String(length=255), nullable=True),
    sa.Column('serie', sa.String(length=50), nullable=True),
    sa.Column('admin_rut', sa.String(length=20), nullable=True),
    sa.Column('admin_dv', sa.String(length=5), nullable=True),
    sa.Column('admin_nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nemotecnico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nemotecnicos')
    # ### end Alembic commands ###
