"""fondo_mutuo table

Revision ID: 74af266f28fb
Revises: 
Create Date: 2026-06-03 20:39:15.384278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74af266f28fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fondo_mutuo',
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('nombre_fondo', sa.String(length=255), nullable=False),
    sa.Column('nombre_corto', sa.String(length=100), nullable=True),
    sa.Column('rut_administradora', sa.String(length=20), nullable=False),
    sa.Column('razon_social_administradora', sa.String(length=255), nullable=False),
    sa.Column('tipo_fondo', sa.String(length=100), nullable=True),
    sa.Column('moneda', sa.String(length=20), nullable=True),
    sa.Column('fecha_inicio_operaciones', sa.Date(), nullable=True),
    sa.Column('fecha_termino_operaciones', sa.Date(), nullable=True),
    sa.Column('fecha_res_aprobacion', sa.Date(), nullable=True),
    sa.Column('nro_res_aprobacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('run_fondo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fondo_mutuo')
    # ### end Alembic commands ###
