"""cartola_diaria table

Revision ID: 7a656d519eda
Revises: 74af266f28fb
Create Date: 2026-06-03 21:00:46.302788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a656d519eda'
down_revision: Union[str, None] = '74af266f28fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
