"""add financial_statements table

Revision ID: cd6b80f447dc
Revises: 478f23a5c713
Create Date: 2026-06-06 16:49:01.127142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd6b80f447dc'
down_revision: Union[str, None] = '478f23a5c713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('consolidation_type', sa.String(length=1), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('account', sa.Text(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('statement_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fs_periodo_rut', 'financial_statements', ['periodo', 'rut'], unique=False)
    op.create_index('ix_fs_rut', 'financial_statements', ['rut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fs_rut', table_name='financial_statements')
    op.drop_index('ix_fs_periodo_rut', table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
