"""add bonos_nemotecnicos table

Revision ID: f163fb9fc0c8
Revises: 0c3bf6dfc418
Create Date: 2026-06-03 23:09:05.084355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f163fb9fc0c8'
down_revision: Union[str, None] = '0c3bf6dfc418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonos_nemotecnicos',
    sa.Column('nemotecnico', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('nombre_emisor', sa.String(length=255), nullable=True),
    sa.Column('rut_emisor', sa.String(length=20), nullable=True),
    sa.Column('numero_inscripcion', sa.String(length=50), nullable=True),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=True),
    sa.Column('fecha_colocacion', sa.Date(), nullable=True),
    sa.Column('tasa_fiscal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('nemotecnico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bonos_nemotecnicos')
    # ### end Alembic commands ###
