"""add categoria_fi table

Revision ID: fa83108ba94b
Revises: 2334f98e82b7
Create Date: 2026-06-07 13:24:20.607996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa83108ba94b'
down_revision: Union[str, None] = '2334f98e82b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_fi',
    sa.Column('run_fondo', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('grupo', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre_cat', sa.String(length=60), nullable=False),
    sa.Column('confianza', sa.String(length=10), nullable=False),
    sa.Column('ipsa_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_pe', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_inmob', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_mh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_eq_nac', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_eq_ext', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_deuda_nac', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_deuda_int', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_fof', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_other', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('met_part', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_fondo', 'periodo')
    )
    op.create_index('ix_categoria_fi_categoria', 'categoria_fi', ['categoria'], unique=False)
    op.create_index('ix_categoria_fi_periodo', 'categoria_fi', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categoria_fi_periodo', table_name='categoria_fi')
    op.drop_index('ix_categoria_fi_categoria', table_name='categoria_fi')
    op.drop_table('categoria_fi')
    # ### end Alembic commands ###
